
all:
	@echo "The only supported targets in the root directory are: doc, clean."
	@echo "To build the libxdma library, the Makefiles inside the different platform directories must be used."

doc:
	doxygen

.PHONY: clean
clean:
	rm -rf html latex
